apiVersion: apps/v1
kind: Deployment
metadata:
  name: ANA-Shopping
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: 343531455648.dkr.ecr.ap-northeast-2.amazonaws.com/ana-test-ecr-repo:was
        imagePullPolicy: Always
        name: was
        ports:
        - containerPort: 8080
