apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: 343531455648.dkr.ecr.ap-northeast-2.amazonaws.com/ana-test-shop:web
        name:  web
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 300Mi 
